--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.127.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 4/2/2021 4:31:44 AM
-- Server version: 15.00.2070
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

USE FDEC
GO

IF DB_NAME() <> N'FDEC' SET NOEXEC ON
GO

--
-- Create table [dbo].[Users]
--
PRINT (N'Create table [dbo].[Users]')
GO
CREATE TABLE dbo.Users (
  ID int IDENTITY,
  Username nvarchar(50) NOT NULL,
  Password nvarchar(50) NOT NULL,
  Role int NULL,
  Fullname nvarchar(50) NULL,
  Address nvarchar(100) NULL,
  Email varchar(50) NULL,
  dob datetime NULL,
  CONSTRAINT PK_Users_id PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Shops]
--
PRINT (N'Create table [dbo].[Shops]')
GO
CREATE TABLE dbo.Shops (
  ID int IDENTITY,
  Name nvarchar(50) NOT NULL,
  Address nvarchar(50) NOT NULL,
  Phone varchar(10) NOT NULL,
  CONSTRAINT PK_Shops_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Products]
--
PRINT (N'Create table [dbo].[Products]')
GO
CREATE TABLE dbo.Products (
  ID int IDENTITY,
  Name nvarchar(50) NOT NULL,
  Description nvarchar(100) NULL,
  ShopID int NOT NULL,
  Image nvarchar(199) NULL,
  Price float NOT NULL,
  CategoryID int NOT NULL,
  CONSTRAINT PK_Products_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Orders]
--
PRINT (N'Create table [dbo].[Orders]')
GO
CREATE TABLE dbo.Orders (
  ID int IDENTITY,
  CreaterID int NOT NULL,
  ShipperID int NULL,
  CreateDate datetime NOT NULL,
  ExpiredDate datetime NULL,
  SuccessDate datetime NULL,
  AddressFrom int NOT NULL,
  AddressOrder int NOT NULL,
  StatusOrder int NOT NULL,
  ShopID int NULL,
  NumberPhoneOrder varchar(10) NOT NULL,
  Cash float NOT NULL,
  CategoryID int NULL,
  Size varchar(50) NULL,
  WeightID float NOT NULL,
  IsActive bit NOT NULL,
  CONSTRAINT PK_Orders_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Notification]
--
PRINT (N'Create table [dbo].[Notification]')
GO
CREATE TABLE dbo.Notification (
  ID int IDENTITY,
  UserActivityID int NOT NULL,
  Content nvarchar(199) NOT NULL,
  Date datetime NOT NULL
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[DeliveryBy]
--
PRINT (N'Create table [dbo].[DeliveryBy]')
GO
CREATE TABLE dbo.DeliveryBy (
  ID int IDENTITY,
  Name varchar(50) NOT NULL
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[City]
--
PRINT (N'Create table [dbo].[City]')
GO
CREATE TABLE dbo.City (
  ID int IDENTITY,
  Name nvarchar(50) NOT NULL
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Category]
--
PRINT (N'Create table [dbo].[Category]')
GO
CREATE TABLE dbo.Category (
  ID int IDENTITY,
  Name nvarchar(50) NOT NULL,
  CONSTRAINT PK_Category_ID PRIMARY KEY CLUSTERED (ID)
)
ON [PRIMARY]
GO

--
-- Create user [as]
--
PRINT (N'Create user [as]')
GO
CREATE USER [as]
  FOR LOGIN [as]
GO

--
-- Create table [dbo].[RulePrice]
--
PRINT (N'Create table [dbo].[RulePrice]')
GO
CREATE TABLE dbo.RulePrice (
  ID int IDENTITY,
  Weight float NOT NULL,
  Price float NOT NULL
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[RuleOfDistance]
--
PRINT (N'Create table [dbo].[RuleOfDistance]')
GO
CREATE TABLE dbo.RuleOfDistance (
  ID int IDENTITY,
  AddressFrom int NOT NULL,
  AddressOrder int NOT NULL,
  Km float NOT NULL
)
ON [PRIMARY]
GO
-- 
-- Dumping data for table Category
--
PRINT (N'Dumping data for table Category')
SET IDENTITY_INSERT dbo.Category ON
GO
INSERT dbo.Category(ID, Name) VALUES (1, N'Thiết bị điện tử')
INSERT dbo.Category(ID, Name) VALUES (2, N'Giày dép')
INSERT dbo.Category(ID, Name) VALUES (3, N'Đồng hồ')
INSERT dbo.Category(ID, Name) VALUES (4, N'Ô tô, xe máy')
INSERT dbo.Category(ID, Name) VALUES (5, N'Sách')
INSERT dbo.Category(ID, Name) VALUES (6, N'Nhà cửa đời sống')
GO
SET IDENTITY_INSERT dbo.Category OFF
GO
-- 
-- Dumping data for table City
--
PRINT (N'Dumping data for table City')
SET IDENTITY_INSERT dbo.City ON
GO
INSERT dbo.City(ID, Name) VALUES (1, N'Tp. Hà Nội')
INSERT dbo.City(ID, Name) VALUES (2, N'Tp. Hồ Chí Minh')
INSERT dbo.City(ID, Name) VALUES (3, N'Tp. Đà Nẵng')
INSERT dbo.City(ID, Name) VALUES (4, N'Tp. Hải Phòng')
GO
SET IDENTITY_INSERT dbo.City OFF
GO
-- 
-- Dumping data for table DeliveryBy
--
PRINT (N'Dumping data for table DeliveryBy')
-- Table FDEC.dbo.DeliveryBy does not contain any data (it is empty)
-- 
-- Dumping data for table Notification
--
PRINT (N'Dumping data for table Notification')
-- Table FDEC.dbo.Notification does not contain any data (it is empty)
-- 
-- Dumping data for table Orders
--
PRINT (N'Dumping data for table Orders')
SET IDENTITY_INSERT dbo.Orders ON
GO
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (5, 1, 2, '2021-03-29 15:50:44.940', '2021-04-07 15:50:48.713', NULL, 1, 2, 0, 1, '0980000001', 1000000, 1, '20x10x30', 1, CONVERT(bit, 'True'))
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (6, 1, 0, '2021-04-01 08:57:20.750', '2021-04-01 08:57:20.753', '2021-04-01 08:57:20.753', 1, 2, 1, 0, '0988888888', 17325000, 0, NULL, 4, CONVERT(bit, 'True'))
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (7, 1, 0, '2021-04-01 09:16:58.083', '2021-04-01 09:16:58.087', '2021-04-01 09:16:58.087', 1, 3, 2, 0, '0812797330', 7695000, 0, NULL, 1, CONVERT(bit, 'True'))
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (8, 1, 0, '2021-04-01 15:14:55.070', '2021-04-01 15:14:55.070', '2021-04-01 15:14:55.070', 1, 2, 0, 0, '0812797330', 17325000, 0, NULL, 4, CONVERT(bit, 'True'))
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (9, 1, 0, '2021-04-01 15:45:07.777', '2021-04-01 15:45:07.777', '2021-04-01 15:45:07.777', 1, 4, 0, 0, '0988888889', 124000, 0, NULL, 1, CONVERT(bit, 'True'))
INSERT dbo.Orders(ID, CreaterID, ShipperID, CreateDate, ExpiredDate, SuccessDate, AddressFrom, AddressOrder, StatusOrder, ShopID, NumberPhoneOrder, Cash, CategoryID, Size, WeightID, IsActive) VALUES (10, 1, 0, '2021-04-01 17:09:19.717', '2021-04-01 17:09:19.717', '2021-04-01 17:09:19.717', 1, 3, 0, 0, '0812797830', 789000, 0, NULL, 3, CONVERT(bit, 'True'))
GO
SET IDENTITY_INSERT dbo.Orders OFF
GO
-- 
-- Dumping data for table Products
--
PRINT (N'Dumping data for table Products')
SET IDENTITY_INSERT dbo.Products ON
GO
INSERT dbo.Products(ID, Name, Description, ShopID, Image, Price, CategoryID) VALUES (1, N'Ipad 5', N'máy tính bảng iPad của nhà Apple', 1, N'ipad.jpg', 10000, 1)
INSERT dbo.Products(ID, Name, Description, ShopID, Image, Price, CategoryID) VALUES (3, N'Iphone 12 Pro Max', N'điện thoại Iphone của nhà Apple', 1, N'iphone12promax.jpg', 15000, 1)
GO
SET IDENTITY_INSERT dbo.Products OFF
GO
-- 
-- Dumping data for table RuleOfDistance
--
PRINT (N'Dumping data for table RuleOfDistance')
SET IDENTITY_INSERT dbo.RuleOfDistance ON
GO
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (1, 1, 2, 1730)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (2, 1, 3, 769)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (5, 2, 1, 1730)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (6, 3, 1, 769)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (7, 3, 2, 250)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (8, 2, 3, 250)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (9, 1, 1, 30)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (10, 2, 2, 30)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (11, 3, 3, 30)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (12, 1, 4, 119)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (13, 2, 4, 1677)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (14, 3, 4, 960)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (15, 4, 4, 30)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (16, 4, 1, 119)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (17, 4, 2, 1677)
INSERT dbo.RuleOfDistance(ID, AddressFrom, AddressOrder, Km) VALUES (18, 4, 3, 960)
GO
SET IDENTITY_INSERT dbo.RuleOfDistance OFF
GO
-- 
-- Dumping data for table RulePrice
--
PRINT (N'Dumping data for table RulePrice')
SET IDENTITY_INSERT dbo.RulePrice ON
GO
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (1, 0.5, 5000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (2, 1, 8000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (3, 3, 20000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (4, 5, 25000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (5, 10, 40000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (6, 15, 60000)
INSERT dbo.RulePrice(ID, Weight, Price) VALUES (7, 20, 80000)
GO
SET IDENTITY_INSERT dbo.RulePrice OFF
GO
-- 
-- Dumping data for table Shops
--
PRINT (N'Dumping data for table Shops')
SET IDENTITY_INSERT dbo.Shops ON
GO
INSERT dbo.Shops(ID, Name, Address, Phone) VALUES (1, N'Shop Huynh Apple', N'Hoa Lac', '0980000001')
GO
SET IDENTITY_INSERT dbo.Shops OFF
GO
-- 
-- Dumping data for table Users
--
PRINT (N'Dumping data for table Users')
SET IDENTITY_INSERT dbo.Users ON
GO
INSERT dbo.Users(ID, Username, Password, Role, Fullname, Address, Email, dob) VALUES (1, N'mra', N'mrabc', 1, N'Nguyen Dinh Huynh', N'Hoa Lac', 'mra@gmail.com', '2021-03-01 09:04:58.477')
INSERT dbo.Users(ID, Username, Password, Role, Fullname, Address, Email, dob) VALUES (2, N'mrb', N'mrb', 2, N'Nguyen Van A', N'Hoa Lac', 'mrb@gmail.com', '2021-03-29 15:57:53.267')
GO
SET IDENTITY_INSERT dbo.Users OFF
GO
SET NOEXEC OFF
GO